import { Pipe, PipeTransform } from '@angular/core';
import { LanguageService } from '../services/language.service';

@Pipe({
  name: 'translate',
  standalone: true,
  pure: false   // Necesario para que se actualice al cambiar el idioma
})
export class TranslatePipe implements PipeTransform {
  private currentLang: string = 'es';
  private translations: any = {};

  constructor(private langService: LanguageService) {
    this.loadTranslations();
    this.langService.currentLang$.subscribe(lang => {
      this.currentLang = lang;
    });
  }

  private loadTranslations() {
    // Diccionario Español (basado en el es.json proporcionado)
    const es: any = {
      "INICIO": "Inicio",
      "BUSCAR": "Buscar",
      "NOTICIAS": "Noticias",
      "CARTERA": "Cartera",
      "PERFIL": "Mi Perfil",
      "CERRAR_SESION": "Cerrar sesión",
      "ANALISIS": "Análisis",
      "MIS_FAVORITOS": "Mis favoritos",
      "ULTIMO_DASHBOARD": "Último dashboard",
      "RESUMEN": "Resumen",
      "HISTORIAL": "Historial",
      "ULTIMAS_NOTICIAS": "Últimas noticias",
      "BUSCAR_NOTICIAS": "Búsqueda avanzada",
      "CONFIGURACION": "Configuración",
      "Slogan": "Análisis financiero en tiempo real, predicciones y sentimiento de noticias",
      "COMENZAR_AHORA": "Comenzar ahora",
      "CARACTERISTICAS_PRINCIPALES": "Características principales",
      "DATOS_HISTORICOS": "Datos históricos",
      "DATOS_HISTORICOS_DESC": "Visualiza el rendimiento pasado de cualquier activo con gráficos interactivos y tablas detalladas.",
      "PREDICCIONES": "Predicciones",
      "PREDICCIONES_DESC": "Predicciones de precios con modelos avanzados (Prophet, ARIMA) y análisis de tendencias.",
      "ANALISIS_SENTIMIENTO": "Análisis de sentimiento",
      "ANALISIS_SENTIMIENTO_DESC": "Noticias financieras clasificadas por sentimiento (positivo, neutral, negativo) con IA.",
      "RESUMEN_MERCADO": "Resumen del mercado",
      "TU_CARTERA_VIRTUAL": "Tu cartera virtual",
      "SIMULA_INVERSIONES": "Simula inversiones sin riesgo y aprende a gestionar tus activos.",
      "IR_A_MI_CARTERA": "Ir a mi cartera",
      "LISTO_PARA_EMPEZAR": "¿Listo para empezar?",
      "BUSCAR_ACTIVOS": "Buscar activos",
      "APERTURA": "APERTURA",
      "MAXIMO": "MÁXIMO",
      "MINIMO": "MÍNIMO",
      "VARIACION": "VARIACIÓN",
      "RENDIMIENTO_POR_PERIODO": "Rendimiento por período",
      "PERIODO": "Período",
      "RENDIMIENTO": "Rendimiento",
      "SEMANA": "semana",
      "MES": "mes",
      "MESES": "meses",
      "ANO": "año",
      "PRECIO_ACTUAL": "Precio actual",
      "ANALISIS_TECNICO": "Análisis técnico",
      "NOTICIAS_Y_SENTIMIENTO": "Noticias y sentimiento",
      "DATOS_HISTORICOS_TABLA": "Datos históricos",
      "FUNDAMENTAL": "Fundamental",
      "RECOMENDACION_INVERSION": "Recomendación de inversión",
      "CONFIANZA": "Confianza",
      "INDICADORES_TECNICOS": "Indicadores técnicos",
      "SOPORTES_RESISTENCIAS": "Soportes / Resistencias",
      "BACKTEST": "Backtest (Cruce SMA 20/50)",
      "RETORNO_TOTAL": "Retorno total",
      "OPERACIONES": "Operaciones",
      "PRECISION_ESTIMADA": "Precisión estimada del modelo",
      "ERROR_MEDIO": "error medio del",
      "CAPITALIZACION_BURSATIL": "Capitalización bursátil",
      "MILES_MILLONES": "miles de millones USD",
      "DIVIDEND_YIELD": "Dividend yield",
      "BENEFICIO_POR_ACCION": "Beneficio por acción (EPS)",
      "BETA": "Beta",
      "MARGEN_BENEFICIO": "Margen de beneficio",
      "NO_HAY_DATOS_FUNDAMENTALES": "No hay datos fundamentales disponibles para este activo.",
      "FAVORITOS": "Favoritos",
      "NO_FAVORITOS": "No tienes acciones favoritas aún.",
      "BUSCAR_SIMBOLO": "Buscar símbolo",
      "VER_DETALLE": "Ver detalle",
      "ELIMINAR": "Eliminar",
      "CARGANDO": "Cargando...",
      "ERROR": "Error",
      "VOLVER": "Volver",
      "REGISTRARSE": "Registrarse",
      "INICIAR_SESION": "Iniciar sesión",
      "EMAIL": "Email",
      "CONTRASENA": "Contraseña",
      "RECORDARME": "Recordarme",
      "OLVIDE_CONTRASENA": "¿Olvidaste tu contraseña?",
      "NO_TIENES_CUENTA": "¿No tienes cuenta?",
      "REGISTRATE": "Regístrate",
      "NOMBRE": "Nombre",
      "APELLIDOS": "Apellidos",
      "CONFIRMAR_CONTRASENA": "Confirmar contraseña",
      "RECUPERAR_CONTRASENA": "Recuperar contraseña",
      "ENVIAR_CODIGO": "Enviar código",
      "CODIGO_VERIFICACION": "Código de verificación",
      "NUEVA_CONTRASENA": "Nueva contraseña",
      "CAMBIAR_CONTRASENA": "Cambiar contraseña",
      "GUARDAR_CAMBIOS": "Guardar cambios",
      "MI_CARTERA_VIRTUAL": "Mi Cartera Virtual",
      "SALDO_DISPONIBLE": "Saldo disponible",
      "MIS_ACCIONES": "Mis acciones",
      "NO_ACCIONES_CARTERA": "No tienes acciones en cartera.",
      "SIMBOLO": "Símbolo",
      "CANTIDAD": "Cantidad",
      "COMPRAR_ACCIONES": "Comprar acciones",
      "SIMBOLO_EJ": "Símbolo (ej. AAPL)",
      "PRECIO_USD": "Precio (USD)",
      "COMPRAR": "Comprar",
      "VENDER_ACCIONES": "Vender acciones",
      "VENDER": "Vender",
      "HISTORIAL_TRANSACCIONES": "Historial de transacciones",
      "ENTRAR": "Entrar",
      "YA_TIENES_CUENTA": "¿Ya tienes cuenta?",
      "CONTRASENA_ACTUAL": "Contraseña actual (solo si quieres cambiarla)",
      "NOTICIAS_FINANCIERAS": "Noticias financieras",
      "BUSCAR_POR_PALABRA_CLAVE": "Buscar por palabra clave",
      "DESDE": "Desde",
      "HASTA": "Hasta",
      "ORDENAR_POR": "Ordenar por:",
      "FECHA_RECIENTE": "Fecha (reciente)",
      "FECHA_ANTIGUO": "Fecha (antiguo)",
      "SENTIMIENTO": "Sentimiento",
      "RESUMEN_SENTIMIENTO": "Resumen de sentimiento",
      "POSITIVO": "Positivo",
      "NEUTRAL": "Neutral",
      "NEGATIVO": "Negativo",
      "EJ_APPLE": "Ej: Apple, Bitcoin, inflación...",
      "NO_HAY_DATOS_SUFICIENTES": "No hay datos suficientes para realizar el análisis.",
      "NO_SE_ENCONTRARON_NOTICIAS": "No se encontraron noticias para ",
      "TOTAL": "Total",
      "TIPO": "Tipo",
      "FECHA": "Fecha",
      "EJEMPLO_SIMBOLO": "Ejemplo: AAPL, BTC-USD, EURUSD...",
      "PRUEBA_EJEMPLOS": "Prueba con ejemplos como Apple, Bitcoin, inflación...",
      "BOLLINGER_SUPERIOR": "Bollinger Superior",
      "BOLLINGER_INFERIOR": "Bollinger Inferior",
      "SOPORTE_CERCANO": "Soporte cercano",
      "RESISTENCIA_CERCANA": "Resistencia cercana",
      "ESTOCASTICO": "Estocástico %K",
      "VER_VELAS": "📊 Ver velas",
      "VER_LINEAS": "📈 Ver líneas",
      "PRECIO_CIERRE": "Precio Cierre",
      "NOTICIAS_RELACIONADAS": "Noticias relacionadas y análisis de sentimiento",
      "NO_DATOS_RANGO": "No hay datos para el rango seleccionado",
      "VOLUMEN": "Volumen",
      "MANTENER": "Mantener",
      "positivo": "Positivo",
      "neutral": "Neutral",
      "negativo": "Negativo",
      "REGISTER": {
        "TITLE": "Registro",
        "NAME_LABEL": "Nombre",
        "NAME_PLACEHOLDER": "Ingresa tu nombre completo",
        "EMAIL_LABEL": "Correo electrónico",
        "EMAIL_PLACEHOLDER": "usuario@ejemplo.com",
        "PASSWORD_LABEL": "Contraseña",
        "PASSWORD_PLACEHOLDER": "Mínimo 6 caracteres",
        "BUTTON": "Registrarse",
        "HAVE_ACCOUNT": "¿Ya tienes cuenta?",
        "LOGIN_LINK": "Inicia sesión",
        "SUCCESS": "¡Registro exitoso! Bienvenido, {{name}}.",
        "ERROR_EMAIL_EXISTS": "Este correo ya está registrado."
      },
      "REGISTER_NAME_PLACEHOLDER": "Tu nombre completo",
      "REGISTER_EMAIL_PLACEHOLDER": "ejemplo@correo.com",
      "REGISTER_PASSWORD_PLACEHOLDER": "Mínimo 6 caracteres",
      "REGISTER_SUCCESS": "¡Registro exitoso! Bienvenido, {{name}}. Redirigiendo al login...",
      "REGISTER_ERROR_GENERIC": "Error al registrarse. Intenta de nuevo.",
      "REGISTER_ERROR_EMAIL_EXISTS": "Este correo electrónico ya está registrado.",
      "REGISTER_ERROR_WEAK_PASSWORD": "La contraseña es demasiado débil. Usa al menos 6 caracteres.",
      "MARKET_HEARTBEAT": "El latido del mercado",
      "FOOTER_DESCRIPTION": "Análisis financiero y recomendaciones para inversores.",
      "ENLACES_RAPIDOS": "Enlaces rápidos",
      "LEGAL": "Legal",
      "CONTACTO": "Contacto",
      "TERMINOS_USO": "Términos de uso",
      "POLITICA_PRIVACIDAD": "Política de privacidad",
      "COOKIES": "Cookies",
      "COPYRIGHT": "Todos los derechos reservados.",
      "TOOLTIP_RESUMEN": "Muestra un resumen con gráfico de precios, KPIs y rendimiento por período.",
      "TOOLTIP_ANALISIS_TECNICO": "Indicadores técnicos como RSI, MACD, medias móviles, soportes y resistencias, más un backtest.",
      "TOOLTIP_NOTICIAS_Y_SENTIMIENTO": "Noticias relacionadas con el activo, analizadas con IA para determinar el sentimiento (positivo, neutral, negativo).",
      "TOOLTIP_DATOS_HISTORICOS": "Tabla con todos los precios históricos (apertura, cierre, máximo, mínimo) del período seleccionado.",
      "TOOLTIP_FUNDAMENTAL": "Datos financieros de la empresa: capitalización, PER, dividendos, etc.",
      "TOOLTIP_RSI": "El Índice de Fuerza Relativa (RSI) mide la magnitud de los cambios recientes para evaluar condiciones de sobrecompra o sobreventa. Por debajo de 30: infravalorado. Por encima de 70: sobrevalorado.",
      "TOOLTIP_MACD": "MACD (Moving Average Convergence Divergence) muestra la relación entre dos medias móviles. Cuando la línea MACD cruza por encima de la señal, es señal alcista.",
      "TOOLTIP_SMA": "Media Móvil Simple (SMA) del precio. SMA20 (corto plazo) y SMA50 (largo plazo). Un cruce alcista ocurre cuando SMA20 supera SMA50.",
      "TOOLTIP_BOLLINGER": "Las Bandas de Bollinger miden la volatilidad. Cuando el precio toca la banda superior, puede estar sobrecomprado; si toca la inferior, sobrevendido.",
      "TOOLTIP_SOPORTE_RESISTENCIA": "Soportes (niveles donde el precio tiende a rebotar al alza) y resistencias (niveles donde tiende a rebotar a la baja).",
      "TOOLTIP_BACKTEST": "Simulación histórica de una estrategia de cruce de medias móviles (SMA20/SMA50). Muestra el retorno total y número de operaciones.",
      "TOOLTIP_MARKET_CAP": "Capitalización bursátil: valor total de la empresa en bolsa. Se calcula multiplicando el número de acciones por el precio actual.",
      "TOOLTIP_PE": "PER (Price-to-Earnings): ratio precio-beneficio. Indica cuántos años de beneficios actuales se necesitan para recuperar la inversión.",
      "TOOLTIP_DIVIDEND": "Dividend Yield: porcentaje del precio de la acción que la empresa paga como dividendo anual.",
      "TOOLTIP_EPS": "Beneficio por Acción (EPS): beneficio neto de la empresa dividido por el número de acciones. Indica la rentabilidad por acción.",
      "TOOLTIP_BETA": "Beta: medida de volatilidad relativa al mercado. Beta > 1 indica más volatilidad que el mercado; Beta < 1 indica menor volatilidad.",
      "TOOLTIP_PROFIT_MARGIN": "Margen de beneficio: porcentaje de los ingresos que se convierte en beneficio neto.",
      "TOOLTIP_FAVORITO": "Añade este activo a tu lista de favoritos para acceder rápidamente desde el menú.",
      "TOOLTIP_BUSCAR_SIMBOLO": "Escribe el símbolo o nombre de una empresa, criptomoneda, índice o divisa. Ejemplos: AAPL, BTC-USD, EURUSD, ^IBEX.",
      "TOOLTIP_CARTERA_SALDO": "Saldo disponible en tu cartera virtual para comprar acciones. Puedes simular inversiones sin riesgo real.",
      "TOOLTIP_COMPRAR": "Compra acciones al precio actual. Necesitas saldo suficiente. Las acciones se añaden a tu cartera.",
      "TOOLTIP_VENDER": "Vende acciones que ya posees. El importe se añade a tu saldo disponible.",
      "TOOLTIP_TRANSACCIONES": "Historial de todas tus compras y ventas, con fecha, cantidad y precio.",
      "TOOLTIP_TOGGLE_CHART": "Cambia entre gráfico de líneas y velas japonesas.",
      "TOOLTIP_CONFIANZA": "Porcentaje de confianza en la recomendación basado en indicadores técnicos.",
      "TOOLTIP_ESTOCASTICO": "Oscilador que compara el precio de cierre con el rango de precios durante un período. Valores >80 indican sobrecompra; <20 sobreventa.",
      "TOOLTIP_MAPE": "Error Medio Absoluto Porcentual (MAPE) - mide la precisión del modelo de predicción. Cuanto menor, mejor.",
      "TOOLTIP_PERIODO_1MO": "Último mes de datos históricos.",
      "TOOLTIP_PERIODO_3MO": "Últimos 3 meses de datos históricos.",
      "TOOLTIP_PERIODO_6MO": "Últimos 6 meses de datos históricos.",
      "TOOLTIP_PERIODO_1Y": "Último año de datos históricos.",
      "BUSCAR_DESCRIPCION": "Encuentra acciones, criptomonedas, índices o divisas. Introduce el símbolo o nombre y accede a análisis completos.",
      "EJEMPLOS_POPULARES": "Ejemplos populares",
      "TIPO_ACCIONES": "Acciones",
      "TIPO_ACCIONES_DESC": "Empresas cotizadas en bolsa. Consulta precios, históricos y fundamentales.",
      "TIPO_CRIPTO": "Criptomonedas",
      "TIPO_CRIPTO_DESC": "Bitcoin, Ethereum y otras. Análisis técnico y predicciones.",
      "TIPO_INDICES": "Índices bursátiles",
      "TIPO_INDICES_DESC": "S&P500, IBEX35, etc. Rendimiento del mercado general.",
      "TIPO_DIVISAS": "Divisas (Forex)",
      "TIPO_DIVISAS_DESC": "Pares de monedas como EUR/USD. Análisis de tendencias.",
      "QUE_OBTENDRAS": "¿Qué obtendrás al buscar?",
      "QUE_OBTENDRAS_DESC": "Gráficos interactivos, predicciones de precios con IA, noticias con análisis de sentimiento, indicadores técnicos y recomendaciones.",
      "TOOLTIP_EJEMPLOS": "Haz clic en cualquier ejemplo para ver su dashboard directamente.",
      "AYUDA_CARTERA": "Ayuda",
      "EVOLUCION": "Evolución",
      "EVOLUCION_CARTERA": "Evolución de tu Cartera",
      "EVOLUCION_EXPLICACION": "Este gráfico muestra cómo ha variado tu saldo disponible a lo largo del tiempo según tus transacciones.",
      "TOOLTIP_CARTERA_RESUMEN": "Resumen de tu saldo y de las acciones que posees actualmente.",
      "TOOLTIP_COMPRAR_EXPLICACION": "Compra acciones introduciendo el símbolo, cantidad y precio actual. Necesitas saldo suficiente.",
      "TOOLTIP_VENDER_EXPLICACION": "Vende acciones que ya tengas en tu cartera. Introduce símbolo, cantidad y precio de venta.",
      "TOOLTIP_TRANSACCIONES_EXPLICACION": "Listado completo de todas tus operaciones de compra y venta, con fecha, cantidad y precio.",
      "TOOLTIP_EVOLUCION_EXPLICACION": "Evolución de tu patrimonio a lo largo del tiempo.",
      "TOOLTIP_COMPRAR_BOTON": "Ejecuta la orden de compra de las acciones.",
      "TOOLTIP_VENDER_BOTON": "Ejecuta la orden de venta de las acciones.",
      "COMPRAR_EXPLICACION": "Compra acciones al precio de mercado. Añade las acciones a tu cartera y reduce tu saldo.",
      "VENDER_EXPLICACION": "Vende acciones que ya posees. El importe se añade a tu saldo disponible.",
      "TRANSACCIONES_EXPLICACION": "Historial de todas tus compras y ventas. Puedes consultar cada transacción en detalle.",
      "CARGANDO_ANALISIS_TECNICO": "Cargando análisis técnico...",
      "AYUDA_CARTERA_TITULO": "Ayuda de la Cartera Virtual",
      "QUE_ES_CARTERA": "¿Qué es la Cartera Virtual?",
      "CARTERA_DESCRIPCION": "La Cartera Virtual es una herramienta de simulación sin riesgo real. Te permite practicar la compra y venta de acciones con dinero ficticio, aprender a gestionar inversiones y probar estrategias antes de invertir dinero real.",
      "COMO_USAR": "Cómo usar la Cartera",
      "COMO_USAR_COMPRAR": "Compra acciones introduciendo el símbolo (ej. AAPL), cantidad y precio actual. Necesitarás saldo suficiente.",
      "COMO_USAR_VENDER": "Vende acciones que ya hayas comprado. Introduce el símbolo, cantidad y precio de venta.",
      "COMO_USAR_HISTORIAL": "Consulta todas tus transacciones pasadas en la pestaña 'Transacciones'.",
      "COMO_USAR_EVOLUCION": "Revisa el gráfico de 'Evolución' para ver cómo ha cambiado tu saldo con el tiempo.",
      "PORQUE_VIRTUAL": "¿Por qué es útil una cartera virtual?",
      "VIRTUAL_EXPLICACION": "Te permite experimentar sin miedo a perder dinero real, entender la volatilidad del mercado y ganar confianza antes de invertir realmente.",
      "CONSEJO_FINAL": "Consejo: Empieza con pequeñas cantidades y diversifica. ¡La práctica hace al maestro!",
      "MI_CARTERA": "Mi cartera",
      "PRECIO_ACTUAL_AUTO": "Precio actual (automático)",
      "COSTE_TOTAL": "Coste total",
      "INGRESO_TOTAL": "Ingreso total",
      "BUSCAR_ACTIVO": "Buscar activo...",
      "NO_RESULTADOS": "No se encontraron resultados",
      "SELECCIONAR_ACTIVO": "Selecciona un activo de la lista",
      "PRECIO_CARGANDO": "Cargando precio...",
      // Español
      "VALOR_ACCIONES": "Valor de acciones",
      "VALOR_TOTAL": "Valor total del portfolio",
      "COMPOSICION_CARTERA": "Composición de la cartera",
      "ULTIMAS_TRANSACCIONES": "Últimas transacciones",
      "ACCIONES": "acciones",
      "VALOR": "Valor",
      "RENDIMIENTO_NO_REALIZADO": "Rendimiento no realizado",
      "TOOLTIP_PRECIO_ACTUAL": "Precio actual de la acción en el mercado. Se actualiza automáticamente en tiempo real.",
      "AYUDA_NOTICIAS": "Ayuda",
      "AYUDA_NOTICIAS_TITULO": "Ayuda sobre noticias financieras",
      "QUE_ES_NOTICIAS": "¿Qué es esta sección?",
      "NOTICIAS_DESCRIPCION": "Aquí puedes buscar noticias financieras relacionadas con cualquier empresa, activo o tema. Además, cada noticia se analiza automáticamente con inteligencia artificial para determinar su sentimiento (positivo, neutral o negativo).",
      "COMO_USAR_NOTICIAS": "Cómo usar el buscador",
      "COMO_USAR_BUSCAR_PALABRA": "Introduce una palabra clave (ej. Apple, Bitcoin, inflación) y pulsa buscar.",
      "COMO_USAR_FILTROS_FECHA": "Utiliza los filtros de fecha para acotar la búsqueda a un período concreto.",
      "COMO_USAR_ORDENAR_SENTIMIENTO": "Ordena los resultados por fecha o por sentimiento para identificar rápidamente noticias positivas o negativas.",
      "COMO_USAR_VER_DETALLE": "Haz clic en cualquier titular para leer la noticia completa en su fuente original.",
      "PORQUE_SENTIMIENTO": "¿Para qué sirve el análisis de sentimiento?",
      "SENTIMIENTO_EXPLICACION": "El análisis de sentimiento te ayuda a entender rápidamente si las noticias sobre un activo son mayoritariamente positivas, neutrales o negativas. Puedes usarlo para tomar decisiones informadas en tus inversiones.",
      "CONSEJO_NOTICIAS": "Consejo: Busca noticias de empresas que te interesen y observa la evolución del sentimiento a lo largo del tiempo. Si notas un cambio brusco, merece la pena investigar más a fondo.",
      "NOTICIAS_EXPLICACION_RAPIDA": "Encuentra las últimas noticias financieras y descubre su sentimiento gracias a la IA.",
      "TOOLTIP_NOTICIAS_EXPLICACION": "El sentimiento se calcula con el modelo FinBERT, especializado en lenguaje financiero.",
      "TOOLTIP_ORDEN_FECHA_DESC": "Las noticias más recientes primero.",
      "TOOLTIP_ORDEN_FECHA_ASC": "Las noticias más antiguas primero.",
      "TOOLTIP_ORDEN_SENTIMIENTO": "Agrupa las noticias por sentimiento: positivo, neutral y negativo.",
      "TOOLTIP_SENTIMIENTO_RESUMEN": "Resumen del sentimiento global de todas las noticias encontradas.",
      "FIABILIDAD_SENTIMIENTO": "¿Qué tan fiable es este análisis?",
      "FIABILIDAD_TEXTO": "El modelo FinBERT ha sido entrenado con grandes volúmenes de textos financieros y alcanza una precisión en torno al 85-90% en tareas de clasificación de sentimiento. Sin embargo, ningún modelo es perfecto: el contexto, el sarcasmo o noticias muy ambiguas pueden llevar a clasificaciones erróneas. Recomendamos usar esta herramienta como complemento a tu propio criterio.",
      "COMO_USAR_NOTICIAS_BUSCAR": "Introduce una palabra clave (empresa, sector, evento) y pulsa 'Buscar'.",
      "COMO_USAR_NOTICIAS_FILTRAR": "Usa las sugerencias rápidas para acceder a temas populares.",
      "COMO_USAR_NOTICIAS_SENTIMIENTO": "Cada noticia se etiqueta automáticamente con su sentimiento (positivo, neutral, negativo).",
      "COMO_USAR_NOTICIAS_ORDENAR": "Ordena los resultados por fecha o por sentimiento.",
      "SENTIMIENTO_TEXTO": "El análisis de sentimiento te ayuda a entender rápidamente si las noticias sobre un activo son mayoritariamente positivas, neutrales o negativas. Puedes usarlo para tomar decisiones informadas en tus inversiones.",
      "TOOLTIP_NOTICIAS_QUERY": "Escribe palabras clave como empresa, sector, criptomoneda o término económico. Por ejemplo: Bitcoin, Apple, inflación, Fed.",
      "TOOLTIP_NOTICIAS_BUSCAR": "Ejecuta la búsqueda de noticias con el término introducido. Se mostrarán hasta 30 artículos recientes.",
      "TOOLTIP_SUGERENCIA": "Haz clic para buscar noticias sobre este tema popular. Es una forma rápida de explorar sin teclear.",
      "VISTA_UNIFICADA": "Vista unificada",
      "VISTA_SEPARADA": "Vista separada",
      "TOOLTIP_VISTA_UNIFICADA": "Muestra histórico y predicción en el mismo gráfico.",
      "TOOLTIP_VISTA_SEPARADA": "Muestra el histórico y la predicción en gráficos separados para mejor claridad.",
      "GRAFICO_HISTORICO": "Datos históricos",
      "GRAFICO_PREDICCION": "Proyección a futuro",
      "GRAFICAS": "Gráficas",
      "TOOLTIP_GRAFICAS": "Visualiza los datos históricos y predicciones en diferentes formatos de gráfico.",
      "AYUDA_GRAFICAS": "Los gráficos muestran la evolución histórica del precio (en velas japonesas o líneas) y la proyección futura con intervalos de confianza. Puedes hacer zoom con el deslizador inferior y ver valores exactos al pasar el ratón.",
      "GRAFICO_UNIFICADO_TITULO": "Visión conjunta (histórico + predicción)",
      "AYUDA_GRAFICO_UNIFICADO": "Gráfico que combina datos pasados (izquierda) con predicción (derecha, línea discontinua). Usa el botón \"Ver velas\" para cambiar el estilo.",
      "AYUDA_GRAFICO_HISTORICO": "Gráfico de velas japonesas: cada vela muestra apertura, máximo, mínimo y cierre de un período. Velas verdes = subida, rojas = bajada.",
      "AYUDA_GRAFICO_PREDICCION": "Proyección futura del precio basada en modelo Prophet. La línea discontinua es la predicción; las bandas representan la incertidumbre (intervalos de confianza).",
      "TOOLTIP_GRAFICAS_AYUDA": "Información sobre cómo interpretar los gráficos.",
      "LEGEND_HISTORICO": "Histórico",
      "LEGEND_PREDICCION": "Predicción",
      "LEGEND_VELAS": "Precio (velas)",
      "LEGEND_INTERVALO_SUPERIOR": "Intervalo superior",
      "LEGEND_INTERVALO_INFERIOR": "Intervalo inferior",
      "LEGEND_HISTORICO_VELAS": "Precio histórico (velas)",
      "AYUDA_ANALISIS": "Ayuda",
      "AYUDA_ANALISIS_TITULO": "Ayuda sobre Análisis",
      "QUE_ES_ANALISIS": "¿Qué es el análisis de activos?",
      "ANALISIS_DESCRIPCION": "FinancialPulse te ofrece un análisis completo de cualquier activo financiero (acciones, criptomonedas, índices, divisas) combinando datos históricos, predicciones con IA, indicadores técnicos y análisis fundamental.",
      "SECCIONES_ANALISIS": "Secciones del dashboard",
      "AYUDA_RESUMEN": "KPIs (apertura, máximo, mínimo, variación) y tabla de rendimiento por períodos.",
      "AYUDA_GRAFICAS_2": "Gráficos interactivos con soporte de zoom. Puedes elegir vista unificada (histórico+predicción) o separada, y cambiar entre velas japonesas y líneas.",
      "AYUDA_ANALISIS_TECNICO": "Recomendación de inversión (Comprar/Mantener/Vender) basada en RSI, MACD, medias móviles, bandas de Bollinger, estocástico, soportes/resistencias y backtest de cruce SMA.",
      "AYUDA_NOTICIAS_SENTIMIENTO": "Noticias recientes del activo con análisis de sentimiento (positivo/neutral/negativo) mediante IA.",
      "AYUDA_DATOS_HISTORICOS": "Tabla completa de precios diarios (apertura, máximo, mínimo, cierre, volumen). Puedes filtrar por fechas.",
      "AYUDA_FUNDAMENTAL": "Datos fundamentales de la empresa (capitalización, PER, dividendos, beneficio por acción, beta, margen).",
      "INTERPRETAR_RECOMENDACION": "¿Cómo interpretar la recomendación?",
      "INTERPRETAR_TEXTO": "La recomendación se calcula con una lógica que puntúa indicadores técnicos. 'Comprar' sugiere posible subida, 'Vender' posible bajada y 'Mantener' lateralidad. La confianza (0-100%) indica cuán fuerte es la señal. Úsala como complemento a tu propio análisis.",
      "CONSEJO_ANALISIS": "Consejo: Pasa el ratón por encima de cualquier elemento (⭐, indicadores, pestañas) para ver tooltips explicativos.",
      "PERFIL_INFO": "Información personal",
"PRIVACIDAD_DATOS": "Privacidad y datos",
"DATOS_PERSONALES": "Datos personales",
"SEGURIDAD_Y_ACCESO": "Seguridad y acceso",
"EXPORTAR_DATOS": "Exportar mis datos",
"EXPORTAR_DESCRIPCION": "Descarga un archivo JSON con toda la información que tenemos sobre tu cuenta (perfil, transacciones, favoritos...).",
"EXPORTAR_BOTON": "Exportar datos",
"ELIMINAR_CUENTA": "Eliminar mi cuenta",
"ELIMINAR_DESCRIPCION": "Esta acción es irreversible. Se borrarán todos tus datos personales y el historial de transacciones. Tu cuenta no podrá recuperarse.",
"ELIMINAR_BOTON": "Eliminar cuenta permanentemente",
"TOOLTIP_NOMBRE": "Tu nombre completo visible en tu perfil.",
"TOOLTIP_EMAIL": "Correo electrónico asociado a tu cuenta. Se usará para iniciar sesión.",
"TOOLTIP_CONTRASENA_ACTUAL": "Debes introducir tu contraseña actual para poder cambiarla.",
"TOOLTIP_NUEVA_CONTRASENA": "Déjalo en blanco si no quieres modificar la contraseña.",
"CONFIRMAR_ELIMINACION": "¿Estás seguro de que quieres eliminar tu cuenta permanentemente? Esta acción no se puede deshacer.",
// ==================== TÉRMINOS DE USO ====================
"TERMINOS_TITULO": "Términos de uso",
"TERMINOS_ULTIMA_ACT": "Última actualización",
"TERMINOS_ACEPTACION": "Aceptación de los términos",
"TERMINOS_ACEPTACION_TEXTO": "Al acceder y utilizar la aplicación web FinancialPulse, aceptas cumplir con estos términos de uso. Si no estás de acuerdo con alguna parte, no utilices la aplicación.",
"TERMINOS_USO_SERVICIO": "Uso del servicio",
"TERMINOS_USO_TEXTO": "FinancialPulse es una herramienta de simulación y análisis financiero. Los datos mostrados proceden de fuentes externas y no constituyen asesoramiento financiero profesional. Las decisiones de inversión son responsabilidad exclusiva del usuario.",
"TERMINOS_USO_LISTA1": "No garantizamos la exactitud o integridad de los datos en tiempo real.",
"TERMINOS_USO_LISTA2": "El uso de la aplicación es bajo tu propio riesgo.",
"TERMINOS_USO_LISTA3": "No nos hacemos responsables de pérdidas financieras reales derivadas de simulaciones.",
"TERMINOS_CUENTAS": "Cuentas de usuario",
"TERMINOS_CUENTAS_TEXTO": "Eres responsable de mantener la confidencialidad de tu cuenta y contraseña. Notifícanos inmediatamente cualquier uso no autorizado.",
"TERMINOS_PROPIEDAD_INTELECTUAL": "Propiedad intelectual",
"TERMINOS_PROPIEDAD_TEXTO": "Todo el contenido, código y diseño de FinancialPulse son propiedad de sus desarrolladores y están protegidos por leyes de propiedad intelectual.",
"TERMINOS_RESPONSABILIDAD": "Limitación de responsabilidad",
"TERMINOS_RESPONSABILIDAD_TEXTO": "FinancialPulse no será responsable de daños directos, indirectos, incidentales o consecuentes derivados del uso o la imposibilidad de uso del servicio.",
"TERMINOS_LEY_APLICABLE": "Ley aplicable",
"TERMINOS_LEY_TEXTO": "Estos términos se rigen por la legislación española. Cualquier disputa será sometida a los tribunales de Granada.",
"TERMINOS_MODIFICACIONES": "Modificaciones",
"TERMINOS_MODIFICACIONES_TEXTO": "Nos reservamos el derecho de modificar estos términos en cualquier momento. Los cambios serán notificados a través de la web y son efectivos inmediatamente después de su publicación.",

// ==================== POLÍTICA DE PRIVACIDAD ====================
"PRIVACIDAD_TITULO": "Política de privacidad",
"PRIVACIDAD_ULTIMA_ACT": "Última actualización",
"PRIVACIDAD_INFORMACION_RECOPILADA": "Información que recopilamos",
"PRIVACIDAD_INFORMACION_TEXTO": "Para ofrecerte la mejor experiencia, recopilamos la siguiente información:",
"PRIVACIDAD_INFORMACION_LISTA1": "Datos de registro: Nombre, correo electrónico y contraseña.",
"PRIVACIDAD_INFORMACION_LISTA2": "Datos de actividad: Historial de transacciones, cartera virtual y búsquedas.",
"PRIVACIDAD_INFORMACION_LISTA3": "Datos técnicos: Dirección IP, tipo de navegador y páginas visitadas.",
"PRIVACIDAD_INFORMACION_LISTA4": "Datos de terceros: Información de APIs externas (Yahoo Finance, NewsAPI).",
"PRIVACIDAD_USO_DATOS": "¿Cómo usamos tu información?",
"PRIVACIDAD_USO_TEXTO": "Utilizamos tus datos para: (i) Operar y mantener la aplicación; (ii) Mejorar la experiencia de usuario; (iii) Enviar notificaciones importantes (si aplica); (iv) Cumplir con obligaciones legales.",
"PRIVACIDAD_COMPARTIR_DATOS": "Compartir datos con terceros",
"PRIVACIDAD_COMPARTIR_TEXTO": "No vendemos tus datos personales. Solo compartimos información con proveedores de servicios esenciales (hosting, autenticación) bajo estrictas medidas de seguridad.",
"PRIVACIDAD_SEGURIDAD": "Seguridad de los datos",
"PRIVACIDAD_SEGURIDAD_TEXTO": "Implementamos medidas de seguridad técnicas y organizativas para proteger tu información, incluyendo cifrado de contraseñas y acceso restringido.",
"PRIVACIDAD_DERECHOS_USUARIO": "Tus derechos (RGPD)",
"PRIVACIDAD_DERECHOS_TEXTO": "Tienes derecho a acceder, rectificar, suprimir tus datos (eliminar cuenta) y limitar su tratamiento. Puedes ejercer estos derechos en la sección \"Mi Perfil\" o contactándonos.",

// ==================== POLÍTICA DE COOKIES ====================
"COOKIES_TITULO": "Política de cookies",
"COOKIES_ULTIMA_ACT": "Última actualización",
"COOKIES_QUE_SON": "¿Qué son las cookies?",
"COOKIES_QUE_SON_TEXTO": "Las cookies son pequeños archivos de texto que los sitios web colocan en tu dispositivo para recordar tus preferencias y mejorar la experiencia de navegación.",
"COOKIES_TIPOS": "Tipos de cookies que utilizamos",
"COOKIES_TIPO_NECESARIAS": "Cookies estrictamente necesarias",
"COOKIES_TIPO_NECESARIAS_TEXTO": "Son esenciales para el funcionamiento de la web. Permiten la autenticación, la navegación y el uso de las funcionalidades básicas.",
"COOKIES_TIPO_PREFERENCIAS": "Cookies de preferencias",
"COOKIES_TIPO_PREFERENCIAS_TEXTO": "Recuerdan tus preferencias, como el idioma seleccionado, para ofrecerte una experiencia más personalizada.",
"COOKIES_TIPO_ANALITICAS": "Cookies analíticas / de rendimiento",
"COOKIES_TIPO_ANALITICAS_TEXTO": "Nos ayudan a entender cómo los usuarios interactúan con la web (páginas más visitadas, tiempo de navegación) para mejorar nuestros servicios.",
"COOKIES_GESTION": "¿Cómo gestionar las cookies?",
"COOKIES_GESTION_TEXTO": "Puedes aceptar o rechazar las cookies no esenciales en nuestro banner de consentimiento. También puedes configurar tu navegador para bloquear o eliminar cookies. Consulta la ayuda de tu navegador para más información.",
"COOKIES_BANNER_TEXTO": "Usamos cookies propias y de terceros para mejorar tu experiencia y analizar el tráfico. Al continuar, aceptas su uso.",
"COOKIES_MAS_INFO": "Más información",
"COOKIES_ACEPTAR": "Aceptar",
"COOKIES_RECHAZAR": "Rechazar",
"MOSTRAR": "Mostrar",
"MOSTRANDO": "Mostrando",
"REGISTROS": "registros",
"DE": "de",
"CARGAR_MAS": "Cargar más",
"MOSTRAR_MENOS": "Mostrar menos"
    };



    // Diccionario Inglés (basado en el en.json proporcionado)
    const en: any = {
      "INICIO": "Home",
      "BUSCAR": "Search",
      "NOTICIAS": "News",
      "CARTERA": "Portfolio",
      "PERFIL": "My Profile",
      "CERRAR_SESION": "Logout",
      "ANALISIS": "Analysis",
      "MIS_FAVORITOS": "My Favorites",
      "ULTIMO_DASHBOARD": "Last dashboard",
      "RESUMEN": "Summary",
      "HISTORIAL": "History",
      "ULTIMAS_NOTICIAS": "Latest news",
      "BUSCAR_NOTICIAS": "Advanced search",
      "CONFIGURACION": "Settings",
      "Slogan": "Real-time financial analysis, predictions and news sentiment",
      "COMENZAR_AHORA": "Start now",
      "CARACTERISTICAS_PRINCIPALES": "Main features",
      "DATOS_HISTORICOS": "Historical data",
      "DATOS_HISTORICOS_DESC": "View past performance of any asset with interactive charts and detailed tables.",
      "PREDICCIONES": "Predictions",
      "PREDICCIONES_DESC": "Price predictions with advanced models (Prophet, ARIMA) and trend analysis.",
      "ANALISIS_SENTIMIENTO": "Sentiment analysis",
      "ANALISIS_SENTIMIENTO_DESC": "Financial news classified by sentiment (positive, neutral, negative) with AI.",
      "RESUMEN_MERCADO": "Market summary",
      "TU_CARTERA_VIRTUAL": "Your virtual portfolio",
      "SIMULA_INVERSIONES": "Simulate risk-free investments and learn to manage your assets.",
      "IR_A_MI_CARTERA": "Go to my portfolio",
      "LISTO_PARA_EMPEZAR": "Ready to start?",
      "BUSCAR_ACTIVOS": "Search assets",
      "APERTURA": "OPEN",
      "MAXIMO": "HIGH",
      "MINIMO": "LOW",
      "VARIACION": "CHANGE",
      "RENDIMIENTO_POR_PERIODO": "Performance by period",
      "PERIODO": "Period",
      "RENDIMIENTO": "Performance",
      "SEMANA": "week",
      "MES": "month",
      "MESES": "months",
      "ANO": "year",
      "PRECIO_ACTUAL": "Current price",
      "ANALISIS_TECNICO": "Technical analysis",
      "NOTICIAS_Y_SENTIMIENTO": "News & sentiment",
      "DATOS_HISTORICOS_TABLA": "Historical data",
      "FUNDAMENTAL": "Fundamental",
      "RECOMENDACION_INVERSION": "Investment recommendation",
      "CONFIANZA": "Confidence",
      "INDICADORES_TECNICOS": "Technical indicators",
      "SOPORTES_RESISTENCIAS": "Supports / Resistances",
      "BACKTEST": "Backtest (SMA Cross 20/50)",
      "RETORNO_TOTAL": "Total return",
      "OPERACIONES": "Trades",
      "PRECISION_ESTIMADA": "Estimated model accuracy",
      "ERROR_MEDIO": "average error of",
      "CAPITALIZACION_BURSATIL": "Market cap",
      "MILES_MILLONES": "billion USD",
      "DIVIDEND_YIELD": "Dividend yield",
      "BENEFICIO_POR_ACCION": "Earnings per share (EPS)",
      "BETA": "Beta",
      "MARGEN_BENEFICIO": "Profit margin",
      "NO_HAY_DATOS_FUNDAMENTALES": "No fundamental data available for this asset.",
      "FAVORITOS": "Favorites",
      "NO_FAVORITOS": "You have no favorite stocks yet.",
      "BUSCAR_SIMBOLO": "Search symbol",
      "VER_DETALLE": "View details",
      "ELIMINAR": "Delete",
      "CARGANDO": "Loading...",
      "ERROR": "Error",
      "VOLVER": "Back",
      "REGISTRARSE": "Register",
      "INICIAR_SESION": "Login",
      "EMAIL": "Email",
      "CONTRASENA": "Password",
      "RECORDARME": "Remember me",
      "OLVIDE_CONTRASENA": "Forgot password?",
      "NO_TIENES_CUENTA": "Don't have an account?",
      "REGISTRATE": "Sign up",
      "NOMBRE": "First name",
      "APELLIDOS": "Last name",
      "CONFIRMAR_CONTRASENA": "Confirm password",
      "RECUPERAR_CONTRASENA": "Reset password",
      "ENVIAR_CODIGO": "Send code",
      "CODIGO_VERIFICACION": "Verification code",
      "NUEVA_CONTRASENA": "New password",
      "CAMBIAR_CONTRASENA": "Change password",
      "GUARDAR_CAMBIOS": "Save changes",
      "MI_CARTERA_VIRTUAL": "My Virtual Portfolio",
      "SALDO_DISPONIBLE": "Available balance",
      "MIS_ACCIONES": "My stocks",
      "NO_ACCIONES_CARTERA": "You have no stocks in your portfolio.",
      "SIMBOLO": "Symbol",
      "CANTIDAD": "Quantity",
      "COMPRAR_ACCIONES": "Buy stocks",
      "SIMBOLO_EJ": "Symbol (e.g. AAPL)",
      "PRECIO_USD": "Price (USD)",
      "COMPRAR": "Buy",
      "VENDER_ACCIONES": "Sell stocks",
      "VENDER": "Sell",
      "HISTORIAL_TRANSACCIONES": "Transaction history",
      "ENTRAR": "Login",
      "YA_TIENES_CUENTA": "Already have an account?",
      "CONTRASENA_ACTUAL": "Current password (only if you want to change it)",
      "NOTICIAS_FINANCIERAS": "Financial news",
      "BUSCAR_POR_PALABRA_CLAVE": "Search by keyword",
      "DESDE": "From",
      "HASTA": "To",
      "ORDENAR_POR": "Sort by:",
      "FECHA_RECIENTE": "Recent date",
      "FECHA_ANTIGUO": "Old date",
      "SENTIMIENTO": "Sentiment",
      "RESUMEN_SENTIMIENTO": "Sentiment summary",
      "POSITIVO": "Positive",
      "NEUTRAL": "Neutral",
      "NEGATIVO": "Negative",
      "EJ_APPLE": "E.g. Apple, Bitcoin, inflation...",
      "NO_HAY_DATOS_SUFICIENTES": "Not enough data to perform analysis.",
      "NO_SE_ENCONTRARON_NOTICIAS": "No news found for ",
      "FECHA": "Date",
      "TIPO": "Type",
      "TOTAL": "Total",
      "EJEMPLO_SIMBOLO": "Example: AAPL, BTC-USD, EURUSD...",
      "PRUEBA_EJEMPLOS": "Try with examples like Apple, Bitcoin, inflation...",
      "BOLLINGER_SUPERIOR": "Upper Bollinger",
      "BOLLINGER_INFERIOR": "Lower Bollinger",
      "SOPORTE_CERCANO": "Near support",
      "RESISTENCIA_CERCANA": "Near resistance",
      "ESTOCASTICO": "Stochastic %K",
      "VER_VELAS": "📊 View candles",
      "VER_LINEAS": "📈 View lines",
      "PRECIO_CIERRE": "Close Price",
      "NOTICIAS_RELACIONADAS": "Related news and sentiment analysis",
      "NO_DATOS_RANGO": "No data for selected range",
      "VOLUMEN": "Volume",
      "MANTENER": "Hold",
      "positivo": "Positive",
      "neutral": "Neutral",
      "negativo": "Negative",
      "REGISTER": {
        "TITLE": "Register",
        "NAME_LABEL": "Name",
        "NAME_PLACEHOLDER": "Enter your full name",
        "EMAIL_LABEL": "Email",
        "EMAIL_PLACEHOLDER": "user@example.com",
        "PASSWORD_LABEL": "Password",
        "PASSWORD_PLACEHOLDER": "Minimum 6 characters",
        "BUTTON": "Sign up",
        "HAVE_ACCOUNT": "Already have an account?",
        "LOGIN_LINK": "Login",
        "SUCCESS": "Registration successful! Welcome, {{name}}.",
        "ERROR_EMAIL_EXISTS": "This email is already registered."
      },
      "REGISTER_NAME_PLACEHOLDER": "Your full name",
      "REGISTER_EMAIL_PLACEHOLDER": "example@email.com",
      "REGISTER_PASSWORD_PLACEHOLDER": "Minimum 6 characters",
      "REGISTER_SUCCESS": "Registration successful! Welcome, {{name}}. Redirecting to login...",
      "REGISTER_ERROR_GENERIC": "Registration failed. Please try again.",
      "REGISTER_ERROR_EMAIL_EXISTS": "This email is already registered.",
      "REGISTER_ERROR_WEAK_PASSWORD": "Password is too weak. Use at least 6 characters.",
      "MARKET_HEARTBEAT": "The market's heartbeat",
      "FOOTER_DESCRIPTION": "Financial analysis and investment recommendations.",
      "ENLACES_RAPIDOS": "Quick links",
      "LEGAL": "Legal",
      "CONTACTO": "Contact",
      "TERMINOS_USO": "Terms of use",
      "POLITICA_PRIVACIDAD": "Privacy policy",
      "COOKIES": "Cookies",
      "COPYRIGHT": "All rights reserved.",
      "TOOLTIP_RESUMEN": "Shows a summary with price chart, KPIs and period performance.",
      "TOOLTIP_ANALISIS_TECNICO": "Technical indicators like RSI, MACD, moving averages, supports and resistances, plus a backtest.",
      "TOOLTIP_NOTICIAS_Y_SENTIMIENTO": "News related to the asset, analyzed with AI to determine sentiment (positive, neutral, negative).",
      "TOOLTIP_DATOS_HISTORICOS": "Table with all historical prices (open, close, high, low) for the selected period.",
      "TOOLTIP_FUNDAMENTAL": "Company financial data: market cap, P/E, dividends, etc.",
      "TOOLTIP_RSI": "Relative Strength Index (RSI) measures the magnitude of recent changes to evaluate overbought or oversold conditions. Below 30: oversold. Above 70: overbought.",
      "TOOLTIP_MACD": "MACD shows the relationship between two moving averages. When the MACD line crosses above the signal line, it's a bullish signal.",
      "TOOLTIP_SMA": "Simple Moving Average (SMA) of the price. SMA20 (short term) and SMA50 (long term). A bullish crossover occurs when SMA20 crosses above SMA50.",
      "TOOLTIP_BOLLINGER": "Bollinger Bands measure volatility. When price touches the upper band, it may be overbought; if it touches the lower band, oversold.",
      "TOOLTIP_SOPORTE_RESISTENCIA": "Supports (levels where price tends to bounce up) and resistances (levels where price tends to bounce down).",
      "TOOLTIP_BACKTEST": "Historical simulation of a moving average crossover strategy (SMA20/SMA50). Shows total return and number of trades.",
      "TOOLTIP_MARKET_CAP": "Market capitalization: total value of the company on the stock market. Calculated by multiplying number of shares by current price.",
      "TOOLTIP_PE": "P/E ratio: price-to-earnings ratio. Indicates how many years of current earnings are needed to recover the investment.",
      "TOOLTIP_DIVIDEND": "Dividend yield: percentage of the stock price that the company pays as an annual dividend.",
      "TOOLTIP_EPS": "Earnings per Share (EPS): net profit divided by number of shares. Indicates profitability per share.",
      "TOOLTIP_BETA": "Beta: measure of volatility relative to the market. Beta > 1 means more volatile than the market; Beta < 1 means less volatile.",
      "TOOLTIP_PROFIT_MARGIN": "Profit margin: percentage of revenue that becomes net profit.",
      "TOOLTIP_FAVORITO": "Add this asset to your favorites list for quick access from the menu.",
      "TOOLTIP_BUSCAR_SIMBOLO": "Enter the symbol or name of a company, cryptocurrency, index or currency. Examples: AAPL, BTC-USD, EURUSD, ^IBEX.",
      "TOOLTIP_CARTERA_SALDO": "Available balance in your virtual portfolio to buy stocks. You can simulate risk-free investments.",
      "TOOLTIP_COMPRAR": "Buy stocks at current price. You need sufficient balance. Stocks are added to your portfolio.",
      "TOOLTIP_VENDER": "Sell stocks you already own. The amount is added to your available balance.",
      "TOOLTIP_TRANSACCIONES": "History of all your purchases and sales, with date, quantity and price.",
      "TOOLTIP_TOGGLE_CHART": "Switch between line chart and candlestick chart.",
      "TOOLTIP_CONFIANZA": "Confidence percentage in the recommendation based on technical indicators.",
      "TOOLTIP_ESTOCASTICO": "Oscillator comparing closing price to price range over a period. Values >80 indicate overbought; <20 oversold.",
      "TOOLTIP_MAPE": "Mean Absolute Percentage Error (MAPE) - measures prediction model accuracy. Lower is better.",
      "TOOLTIP_PERIODO_1MO": "Last month of historical data.",
      "TOOLTIP_PERIODO_3MO": "Last 3 months of historical data.",
      "TOOLTIP_PERIODO_6MO": "Last 6 months of historical data.",
      "TOOLTIP_PERIODO_1Y": "Last year of historical data.",
      "BUSCAR_DESCRIPCION": "Find stocks, cryptocurrencies, indices or currencies. Enter the symbol or name to get full analysis.",
      "EJEMPLOS_POPULARES": "Popular examples",
      "TIPO_ACCIONES": "Stocks",
      "TIPO_ACCIONES_DESC": "Publicly traded companies. Check prices, history and fundamentals.",
      "TIPO_CRIPTO": "Cryptocurrencies",
      "TIPO_CRIPTO_DESC": "Bitcoin, Ethereum and more. Technical analysis and predictions.",
      "TIPO_INDICES": "Stock indices",
      "TIPO_INDICES_DESC": "S&P500, IBEX35, etc. Overall market performance.",
      "TIPO_DIVISAS": "Currencies (Forex)",
      "TIPO_DIVISAS_DESC": "Currency pairs like EUR/USD. Trend analysis.",
      "QUE_OBTENDRAS": "What will you get?",
      "QUE_OBTENDRAS_DESC": "Interactive charts, AI-powered price predictions, news sentiment analysis, technical indicators and recommendations.",
      "TOOLTIP_EJEMPLOS": "Click on any example to go directly to its dashboard.",
      "AYUDA_CARTERA": "Help",
      "EVOLUCION": "Evolution",
      "EVOLUCION_CARTERA": "Portfolio Evolution",
      "EVOLUCION_EXPLICACION": "This chart shows how your available balance has changed over time based on your transactions.",
      "TOOLTIP_CARTERA_RESUMEN": "Summary of your balance and current holdings.",
      "TOOLTIP_COMPRAR_EXPLICACION": "Buy stocks by entering symbol, quantity and current price. You need sufficient balance.",
      "TOOLTIP_VENDER_EXPLICACION": "Sell stocks you already own. Enter symbol, quantity and sale price.",
      "TOOLTIP_TRANSACCIONES_EXPLICACION": "Complete list of all your buy and sell operations, with date, quantity and price.",
      "TOOLTIP_EVOLUCION_EXPLICACION": "Evolution of your wealth over time.",
      "TOOLTIP_COMPRAR_BOTON": "Execute the stock purchase order.",
      "TOOLTIP_VENDER_BOTON": "Execute the stock sale order.",
      "COMPRAR_EXPLICACION": "Buy stocks at market price. Adds shares to your portfolio and reduces your balance.",
      "VENDER_EXPLICACION": "Sell stocks you already own. The amount is added to your available balance.",
      "TRANSACCIONES_EXPLICACION": "History of all your purchases and sales. You can view each transaction in detail.",
      "AYUDA_CARTERA_TITULO": "Virtual Portfolio Help",
      "QUE_ES_CARTERA": "What is the Virtual Portfolio?",
      "CARTERA_DESCRIPCION": "The Virtual Portfolio is a risk-free simulation tool. It allows you to practice buying and selling stocks with fictitious money, learn to manage investments and test strategies before investing real money.",
      "COMO_USAR": "How to use the Portfolio",
      "COMO_USAR_COMPRAR": "Buy stocks by entering the symbol (e.g. AAPL), quantity and current price. You will need sufficient balance.",
      "COMO_USAR_VENDER": "Sell stocks you have already bought. Enter the symbol, quantity and sale price.",
      "COMO_USAR_HISTORIAL": "View all your past transactions in the 'Transactions' tab.",
      "COMO_USAR_EVOLUCION": "Check the 'Evolution' chart to see how your balance has changed over time.",
      "PORQUE_VIRTUAL": "Why is a virtual portfolio useful?",
      "VIRTUAL_EXPLICACION": "It allows you to experiment without fear of losing real money, understand market volatility and gain confidence before actually investing.",
      "CONSEJO_FINAL": "Tip: Start with small amounts and diversify. Practice makes perfect!",
      "MI_CARTERA": "My portfolio",
      "PRECIO_ACTUAL_AUTO": "Current price (auto)",
      "COSTE_TOTAL": "Total cost",
      "INGRESO_TOTAL": "Total income",
      "BUSCAR_ACTIVO": "Search asset...",
      "NO_RESULTADOS": "No results found",
      "SELECCIONAR_ACTIVO": "Select an asset from the list",
      "PRECIO_CARGANDO": "Loading price...",
      "VALOR_ACCIONES": "Stocks value",
      "VALOR_TOTAL": "Total portfolio value",
      "COMPOSICION_CARTERA": "Portfolio composition",
      "ULTIMAS_TRANSACCIONES": "Latest transactions",
      "ACCIONES": "shares",
      "VALOR": "Value",
      "RENDIMIENTO_NO_REALIZADO": "Unrealized return",
      "TOOLTIP_PRECIO_ACTUAL": "Current stock price in the market. Automatically updated in real time.",
      "AYUDA_NOTICIAS": "Help",
      "AYUDA_NOTICIAS_TITULO": "Financial news help",
      "QUE_ES_NOTICIAS": "What is this section?",
      "NOTICIAS_DESCRIPCION": "Search for financial news about any company, asset or topic. Each news is automatically analyzed with AI to determine its sentiment (positive, neutral or negative).",
      "COMO_USAR_NOTICIAS": "How to use the search",
      "COMO_USAR_BUSCAR_PALABRA": "Enter a keyword (e.g. Apple, Bitcoin, inflation) and hit search.",
      "COMO_USAR_FILTROS_FECHA": "Use date filters to narrow down to a specific period.",
      "COMO_USAR_ORDENAR_SENTIMIENTO": "Sort results by date or sentiment to quickly identify positive or negative news.",
      "COMO_USAR_VER_DETALLE": "Click on any headline to read the full article on its original source.",
      "PORQUE_SENTIMIENTO": "What is sentiment analysis for?",
      "SENTIMIENTO_EXPLICACION": "Sentiment analysis helps you quickly understand whether news about an asset is mostly positive, neutral or negative. You can use it to make informed investment decisions.",
      "CONSEJO_NOTICIAS": "Tip: Search for news about companies you are interested in and track sentiment over time. If you notice a sudden change, it's worth investigating further.",
      "NOTICIAS_EXPLICACION_RAPIDA": "Find the latest financial news and discover their AI-powered sentiment.",
      "TOOLTIP_NOTICIAS_EXPLICACION": "Sentiment is calculated using the FinBERT model, specialized in financial language.",
      "TOOLTIP_ORDEN_FECHA_DESC": "Most recent news first.",
      "TOOLTIP_ORDEN_FECHA_ASC": "Oldest news first.",
      "TOOLTIP_ORDEN_SENTIMIENTO": "Group news by sentiment: positive, neutral or negative.",
      "TOOLTIP_SENTIMIENTO_RESUMEN": "Overall sentiment summary of all found news.",
      "FIABILIDAD_SENTIMIENTO": "How reliable is this analysis?",
      "FIABILIDAD_TEXTO": "FinBERT has been trained on large volumes of financial texts and achieves around 85-90% accuracy in sentiment classification tasks. However, no model is perfect: context, sarcasm, or very ambiguous news can lead to misclassifications. We recommend using this tool as a supplement to your own judgment.",
      "COMO_USAR_NOTICIAS_BUSCAR": "Enter a keyword (company, sector, event) and click 'Search'.",
      "COMO_USAR_NOTICIAS_FILTRAR": "Use quick suggestions to access popular topics.",
      "COMO_USAR_NOTICIAS_SENTIMIENTO": "Each article is automatically labeled with its sentiment (positive, neutral, negative).",
      "COMO_USAR_NOTICIAS_ORDENAR": "Sort results by date or sentiment.",
      "SENTIMIENTO_TEXTO": "Sentiment analysis helps you quickly understand whether news about an asset is predominantly positive, neutral or negative. Use it to make informed investment decisions.",
      "TOOLTIP_NOTICIAS_QUERY": "Enter keywords like company, sector, cryptocurrency or economic term. For example: Bitcoin, Apple, inflation, Fed.",
      "TOOLTIP_NOTICIAS_BUSCAR": "Run the news search with the entered term. Up to 30 recent articles will be shown.",
      "TOOLTIP_SUGERENCIA": "Click to search news about this popular topic. A quick way to explore without typing.",
      "VISTA_UNIFICADA": "Unified view",
      "VISTA_SEPARADA": "Separate view",
      "TOOLTIP_VISTA_UNIFICADA": "Shows historical and prediction in the same chart.",
      "TOOLTIP_VISTA_SEPARADA": "Shows historical and prediction in separate charts for better clarity.",
      "GRAFICO_HISTORICO": "Historical data",
      "GRAFICO_PREDICCION": "Future projection",
      "GRAFICAS": "Charts",
      "TOOLTIP_GRAFICAS": "View historical data and predictions in different chart formats.",
      "AYUDA_GRAFICAS": "Charts show historical price evolution (candlestick or line) and future projection with confidence bands. Use the bottom slider to zoom and hover for exact values.",
      "GRAFICO_UNIFICADO_TITULO": "Combined view (historical + prediction)",
      "AYUDA_GRAFICO_UNIFICADO": "Chart combining past data (left) with prediction (right, dashed line). Use 'View candles' button to change style.",
      "AYUDA_GRAFICO_HISTORICO": "Japanese candlestick chart: each candle shows open, high, low, close. Green candles = price increase, red = decrease.",
      "AYUDA_GRAFICO_PREDICCION": "Future price projection based on Prophet model. The dashed line is the prediction; bands represent uncertainty (confidence intervals).",
      "TOOLTIP_GRAFICAS_AYUDA": "Information on how to interpret the charts.",
      "LEGEND_HISTORICO": "Historical",
      "LEGEND_PREDICCION": "Prediction",
      "LEGEND_VELAS": "Price (candles)",
      "LEGEND_INTERVALO_SUPERIOR": "Upper band",
      "LEGEND_INTERVALO_INFERIOR": "Lower band",
      "LEGEND_HISTORICO_VELAS": "Historical price (candles)",
      "AYUDA_ANALISIS": "Help",
      "AYUDA_ANALISIS_TITULO": "Analysis Help",
      "QUE_ES_ANALISIS": "What is asset analysis?",
      "ANALISIS_DESCRIPCION": "FinancialPulse provides comprehensive analysis for any financial asset (stocks, cryptocurrencies, indices, currencies) combining historical data, AI predictions, technical indicators, and fundamental analysis.",
      "SECCIONES_ANALISIS": "Dashboard sections",
      "AYUDA_RESUMEN": "KPIs (open, high, low, variation) and period-based performance table.",
      "AYUDA_GRAFICAS_2": "Interactive charts with zoom. You can choose unified view (historical+prediction) or separated, and switch between candlesticks and lines.",
      "AYUDA_ANALISIS_TECNICO": "Investment recommendation (Buy/Hold/Sell) based on RSI, MACD, moving averages, Bollinger bands, stochastic, supports/resistances, and SMA crossover backtest.",
      "AYUDA_NOTICIAS_SENTIMIENTO": "Recent news of the asset with AI-based sentiment analysis (positive/neutral/negative).",
      "AYUDA_DATOS_HISTORICOS": "Complete daily price table (open, high, low, close, volume). You can filter by date range.",
      "AYUDA_FUNDAMENTAL": "Company fundamental data (market cap, P/E, dividends, earnings per share, beta, margin).",
      "INTERPRETAR_RECOMENDACION": "How to interpret the recommendation?",
      "INTERPRETAR_TEXTO": "The recommendation is calculated with a technical indicator scoring logic. 'Buy' suggests possible upward movement, 'Sell' downward movement, and 'Hold' sideways. Confidence (0-100%) indicates signal strength. Use it as a complement to your own analysis.",
      "CONSEJO_ANALISIS": "Tip: Hover over any element (⭐, indicators, tabs) to see explanatory tooltips.",
      "PERFIL_INFO": "Personal information",
"PRIVACIDAD_DATOS": "Privacy & data",
"DATOS_PERSONALES": "Personal details",
"SEGURIDAD_Y_ACCESO": "Security & access",
"EXPORTAR_DATOS": "Export my data",
"EXPORTAR_DESCRIPCION": "Download a JSON file with all the information we have about your account (profile, transactions, favorites...).",
"EXPORTAR_BOTON": "Export data",
"ELIMINAR_CUENTA": "Delete my account",
"ELIMINAR_DESCRIPCION": "This action is irreversible. All your personal data and transaction history will be deleted. Your account cannot be recovered.",
"ELIMINAR_BOTON": "Permanently delete account",
"TOOLTIP_NOMBRE": "Your full name displayed on your profile.",
"TOOLTIP_EMAIL": "Email associated with your account. Used to log in.",
"TOOLTIP_CONTRASENA_ACTUAL": "You must enter your current password to change it.",
"TOOLTIP_NUEVA_CONTRASENA": "Leave blank if you don't want to change your password.",
"CONFIRMAR_ELIMINACION": "Are you sure you want to permanently delete your account? This action cannot be undone.",
// ==================== TERMS OF USE ====================
"TERMINOS_TITULO": "Terms of Use",
"TERMINOS_ULTIMA_ACT": "Last updated",
"TERMINOS_ACEPTACION": "Acceptance of terms",
"TERMINOS_ACEPTACION_TEXTO": "By accessing and using FinancialPulse web application, you agree to comply with these terms of use. If you do not agree with any part, do not use the application.",
"TERMINOS_USO_SERVICIO": "Use of the service",
"TERMINOS_USO_TEXTO": "FinancialPulse is a financial simulation and analysis tool. The data displayed comes from external sources and does not constitute professional financial advice. Investment decisions are the sole responsibility of the user.",
"TERMINOS_USO_LISTA1": "We do not guarantee the accuracy or completeness of real-time data.",
"TERMINOS_USO_LISTA2": "Use of the application is at your own risk.",
"TERMINOS_USO_LISTA3": "We are not responsible for actual financial losses resulting from simulations.",
"TERMINOS_CUENTAS": "User accounts",
"TERMINOS_CUENTAS_TEXTO": "You are responsible for maintaining the confidentiality of your account and password. Notify us immediately of any unauthorized use.",
"TERMINOS_PROPIEDAD_INTELECTUAL": "Intellectual property",
"TERMINOS_PROPIEDAD_TEXTO": "All content, code and design of FinancialPulse are the property of its developers and are protected by intellectual property laws.",
"TERMINOS_RESPONSABILIDAD": "Limitation of liability",
"TERMINOS_RESPONSABILIDAD_TEXTO": "FinancialPulse shall not be liable for direct, indirect, incidental or consequential damages arising from the use or inability to use the service.",
"TERMINOS_LEY_APLICABLE": "Governing law",
"TERMINOS_LEY_TEXTO": "These terms are governed by Spanish law. Any dispute will be submitted to the courts of Granada.",
"TERMINOS_MODIFICACIONES": "Modifications",
"TERMINOS_MODIFICACIONES_TEXTO": "We reserve the right to modify these terms at any time. Changes will be notified through the website and are effective immediately after posting.",

// ==================== PRIVACY POLICY ====================
"PRIVACIDAD_TITULO": "Privacy policy",
"PRIVACIDAD_ULTIMA_ACT": "Last updated",
"PRIVACIDAD_INFORMACION_RECOPILADA": "Information we collect",
"PRIVACIDAD_INFORMACION_TEXTO": "To provide you with the best experience, we collect the following information:",
"PRIVACIDAD_INFORMACION_LISTA1": "Registration data: Name, email and password.",
"PRIVACIDAD_INFORMACION_LISTA2": "Activity data: Transaction history, virtual portfolio and searches.",
"PRIVACIDAD_INFORMACION_LISTA3": "Technical data: IP address, browser type and pages visited.",
"PRIVACIDAD_INFORMACION_LISTA4": "Third-party data: Information from external APIs (Yahoo Finance, NewsAPI).",
"PRIVACIDAD_USO_DATOS": "How we use your information",
"PRIVACIDAD_USO_TEXTO": "We use your data to: (i) Operate and maintain the application; (ii) Improve the user experience; (iii) Send important notifications (if applicable); (iv) Comply with legal obligations.",
"PRIVACIDAD_COMPARTIR_DATOS": "Sharing data with third parties",
"PRIVACIDAD_COMPARTIR_TEXTO": "We do not sell your personal data. We only share information with essential service providers (hosting, authentication) under strict security measures.",
"PRIVACIDAD_SEGURIDAD": "Data security",
"PRIVACIDAD_SEGURIDAD_TEXTO": "We implement technical and organizational security measures to protect your information, including password encryption and restricted access.",
"PRIVACIDAD_DERECHOS_USUARIO": "Your rights (GDPR)",
"PRIVACIDAD_DERECHOS_TEXTO": "You have the right to access, rectify, delete your data (delete account) and restrict its processing. You can exercise these rights in the 'My Profile' section or by contacting us.",

// ==================== COOKIE POLICY ====================
"COOKIES_TITULO": "Cookie policy",
"COOKIES_ULTIMA_ACT": "Last updated",
"COOKIES_QUE_SON": "What are cookies?",
"COOKIES_QUE_SON_TEXTO": "Cookies are small text files that websites place on your device to remember your preferences and improve the browsing experience.",
"COOKIES_TIPOS": "Types of cookies we use",
"COOKIES_TIPO_NECESARIAS": "Strictly necessary cookies",
"COOKIES_TIPO_NECESARIAS_TEXTO": "They are essential for the operation of the website. They allow authentication, navigation and the use of basic functionalities.",
"COOKIES_TIPO_PREFERENCIAS": "Preference cookies",
"COOKIES_TIPO_PREFERENCIAS_TEXTO": "They remember your preferences, such as the selected language, to offer you a more personalized experience.",
"COOKIES_TIPO_ANALITICAS": "Analytical / performance cookies",
"COOKIES_TIPO_ANALITICAS_TEXTO": "They help us understand how users interact with the website (most visited pages, browsing time) to improve our services.",
"COOKIES_GESTION": "How to manage cookies?",
"COOKIES_GESTION_TEXTO": "You can accept or reject non-essential cookies in our consent banner. You can also configure your browser to block or delete cookies. See your browser help for more information.",
"COOKIES_BANNER_TEXTO": "We use our own and third-party cookies to improve your experience and analyze traffic. By continuing, you accept their use.",
"COOKIES_MAS_INFO": "More info",
"COOKIES_ACEPTAR": "Accept",
"COOKIES_RECHAZAR": "Reject",
"MOSTRAR": "Show",
"MOSTRANDO": "Showing",
"REGISTROS": "records",
"DE": "of",
"CARGAR_MAS": "Load more",
"MOSTRAR_MENOS": "Show less"
    };

    this.translations = { es, en };
  }

  transform(key: string, params?: { [key: string]: string | number }): string {
    let value = this.translations[this.currentLang]?.[key];
    if (!value) return key;
    if (params) {
      Object.keys(params).forEach(paramKey => {
        const regex = new RegExp(`{{${paramKey}}}`, 'g');
        value = value.replace(regex, String(params[paramKey]));
      });
    }
    return value;
  }
}